language: node_js
sudo: false
node_js:
    - 7

cache:
    yarn: true
    directories:
        - node_modules

script:
    # Try to build
    - yarn run build
deploy:
    - provider: script
      skip_cleanup: true
      script: "./deploy.sh"
      on:
          all_branches: true
